

export const FETCH_CATAGORIES_TAB = 'FETCH_CATAGORIES_TAB'
export const FETCH_CATAGORIES_TAB_SUCCESS = 'FETCH_CATAGORIES_TAB_SUCCESS'
export const SET_SELECTED_CATAGORIE_ID_AND_NAME = 'SET_SELECTED_CATAGORIE_ID_AND_NAME'


export const FETCH_SELECTED_PRODUCT_LIST = 'FETCH_SELECTED_PRODUCT_LIST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'

export const CHANGE_IS_VIEW_MORE_STATE = 'CHANGE_IS_VIEW_MORE_STATE'

